app            = "multiplayer-fabric-crdb"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source      = "crdb_data"
  destination = "/cockroach/cockroach-data"

[[services]]
  protocol             = "tcp"
  internal_port        = 26257
  auto_stop_machines    = false
  auto_start_machines   = true
  min_machines_running  = 1

[[services]]
  protocol             = "tcp"
  internal_port        = 8080
  auto_stop_machines    = false
  auto_start_machines   = true
  min_machines_running  = 1

  [[services.ports]]
    port = 8080

  [[services.tcp_checks]]
    interval     = "15s"
    timeout      = "5s"
    grace_period = "30s"

[[vm]]
  memory   = "1gb"
  cpu_kind = "shared"
  cpus     = 1
